// <auto-generated />
using HttpProxyService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HttpProxyService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230615192429_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HttpProxyService.Models.AccessLog", b =>
                {
                    b.Property<int>("AccessLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessLogId"));

                    b.Property<string>("LogData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MethodInfoId")
                        .HasColumnType("integer");

                    b.HasKey("AccessLogId");

                    b.HasIndex("MethodInfoId");

                    b.ToTable("accesslogs", "public");
                });

            modelBuilder.Entity("HttpProxyService.Models.MethodInfo", b =>
                {
                    b.Property<int>("MethodInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MethodInfoId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MethodInfoId");

                    b.ToTable("methodinfo", "public");
                });

            modelBuilder.Entity("HttpProxyService.Models.AccessLog", b =>
                {
                    b.HasOne("HttpProxyService.Models.MethodInfo", "MethodInfo")
                        .WithMany("AccessLogs")
                        .HasForeignKey("MethodInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MethodInfo");
                });

            modelBuilder.Entity("HttpProxyService.Models.MethodInfo", b =>
                {
                    b.Navigation("AccessLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
