// <auto-generated />
using System;
using HttpProxyService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HttpProxyService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230618224234_InitDb5")]
    partial class InitDb5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HttpProxyService.Models.AccessLog", b =>
                {
                    b.Property<int>("AccessLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessLogId"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MethodInfoId")
                        .HasColumnType("integer");

                    b.HasKey("AccessLogId");

                    b.HasIndex("MethodInfoId");

                    b.ToTable("accesslogs", "public");
                });

            modelBuilder.Entity("HttpProxyService.Models.MethodInfo", b =>
                {
                    b.Property<int>("MethodInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MethodInfoId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MethodInfoId");

                    b.ToTable("methodinfo", "public");

                    b.HasData(
                        new
                        {
                            MethodInfoId = 1,
                            Name = "StudentProfile",
                            RequestPath = "student_info/profile"
                        },
                        new
                        {
                            MethodInfoId = 2,
                            Name = "StudentOrders",
                            RequestPath = "student_info/orders"
                        },
                        new
                        {
                            MethodInfoId = 3,
                            Name = "StudentStatements",
                            RequestPath = "student_info/statements"
                        },
                        new
                        {
                            MethodInfoId = 4,
                            Name = "EmployeeProfile",
                            RequestPath = "employee_info/profile"
                        },
                        new
                        {
                            MethodInfoId = 5,
                            Name = "EmployeeAttestation",
                            RequestPath = "employee_info/attestation"
                        },
                        new
                        {
                            MethodInfoId = 6,
                            Name = "EmployeeSetMark",
                            RequestPath = "employee_info/setmark"
                        },
                        new
                        {
                            MethodInfoId = 7,
                            Name = "EmployeeMarksList",
                            RequestPath = "employee_info/markslist"
                        });
                });

            modelBuilder.Entity("HttpProxyService.Models.AccessLog", b =>
                {
                    b.HasOne("HttpProxyService.Models.MethodInfo", "MethodInfo")
                        .WithMany("AccessLogs")
                        .HasForeignKey("MethodInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MethodInfo");
                });

            modelBuilder.Entity("HttpProxyService.Models.MethodInfo", b =>
                {
                    b.Navigation("AccessLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
